/**
 * theme-presets.ts — the platform's theme preset catalog (issue #219 1.2).
 *
 * Each preset carries the full branding colour surface so that applying a
 * theme re-colours the whole app (primary/secondary/accent actions, text,
 * page background, navbar and sidebar chrome). Only the keys present here are
 * used; Branding-specific overrides (logo, company name, font) are untouched
 * by a theme apply.
 */
export interface ThemePreset {
  presetName: string;
  presetKey: string;
  description?: string;
  isDefault?: boolean;
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  textColor?: string;
  backgroundColor?: string;
  navbarColor?: string;
  navbarTextColor?: string;
  sidebarColor?: string;
  sidebarTextColor?: string;
  accentHoverColor?: string;
}

export const DEFAULT_THEME_PRESETS: ThemePreset[] = [
  {
    presetName: "Default",
    presetKey: "default",
    isDefault: true,
    description: "Neutral light workspace with a graphite primary.",
    primaryColor: "#1F2937",
    secondaryColor: "#3B82F6",
    accentColor: "#F59E0B",
    textColor: "#111827",
    backgroundColor: "#F2F3EE",
    navbarColor: "#1F2937",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#1F2937",
    sidebarTextColor: "#E5E7EB",
    accentHoverColor: "#D97706",
  },
  {
    presetName: "Classic Blue",
    presetKey: "classic-blue",
    description: "Trustworthy indigo primary, cool slate chrome.",
    primaryColor: "#2563EB",
    secondaryColor: "#3B82F6",
    accentColor: "#F59E0B",
    textColor: "#0F172A",
    backgroundColor: "#F8FAFC",
    navbarColor: "#1E40AF",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#1E293B",
    sidebarTextColor: "#CBD5E1",
    accentHoverColor: "#D97706",
  },
  {
    presetName: "Modern",
    presetKey: "modern",
    description: "Sleek near-black primary with vibrant violet accent.",
    primaryColor: "#111827",
    secondaryColor: "#6366F1",
    accentColor: "#8B5CF6",
    textColor: "#111827",
    backgroundColor: "#FFFFFF",
    navbarColor: "#0F172A",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#0F172A",
    sidebarTextColor: "#94A3B8",
    accentHoverColor: "#7C3AED",
  },
  {
    presetName: "Dark",
    presetKey: "dark",
    description: "Full dark theme for low-light work.",
    primaryColor: "#F8FAFC",
    secondaryColor: "#3B82F6",
    accentColor: "#F59E0B",
    textColor: "#F1F5F9",
    backgroundColor: "#0F172A",
    navbarColor: "#020617",
    navbarTextColor: "#F1F5F9",
    sidebarColor: "#020617",
    sidebarTextColor: "#94A3B8",
    accentHoverColor: "#D97706",
  },
  {
    presetName: "Professional",
    presetKey: "professional",
    description: "Steady navy with warm amber accent.",
    primaryColor: "#1E293B",
    secondaryColor: "#475569",
    accentColor: "#F59E0B",
    textColor: "#0F172A",
    backgroundColor: "#F1F5F9",
    navbarColor: "#1E293B",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#1E293B",
    sidebarTextColor: "#CBD5E1",
    accentHoverColor: "#D97706",
  },
  {
    presetName: "Minimal Green",
    presetKey: "minimal-green",
    description: "Calm green primary, airy light page.",
    primaryColor: "#16A34A",
    secondaryColor: "#22C55E",
    accentColor: "#F59E0B",
    textColor: "#14532D",
    backgroundColor: "#F0FDF4",
    navbarColor: "#166534",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#14532D",
    sidebarTextColor: "#BBF7D0",
    accentHoverColor: "#D97706",
  },
  {
    presetName: "Sunset",
    presetKey: "sunset",
    description: "Warm terracotta primary, soft coral accent.",
    primaryColor: "#EA580C",
    secondaryColor: "#F97316",
    accentColor: "#F43F5E",
    textColor: "#431407",
    backgroundColor: "#FFF7ED",
    navbarColor: "#9A3412",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#7C2D12",
    sidebarTextColor: "#FED7AA",
    accentHoverColor: "#E11D48",
  },
  {
    presetName: "Ocean",
    presetKey: "ocean",
    description: "Deep teal primary, fresh cyan accents.",
    primaryColor: "#0E7490",
    secondaryColor: "#06B6D4",
    accentColor: "#2DD4BF",
    textColor: "#083344",
    backgroundColor: "#ECFEFF",
    navbarColor: "#155E75",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#164E63",
    sidebarTextColor: "#A5F3FC",
    accentHoverColor: "#14B8A6",
  },
  {
    presetName: "Midnight",
    presetKey: "midnight",
    description: "High-contrast slate blue, steel chrome.",
    primaryColor: "#334155",
    secondaryColor: "#64748B",
    accentColor: "#38BDF8",
    textColor: "#0F172A",
    backgroundColor: "#E2E8F0",
    navbarColor: "#0F172A",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#0F172A",
    sidebarTextColor: "#94A3B8",
    accentHoverColor: "#0EA5E9",
  },
  {
    presetName: "Coral",
    presetKey: "coral",
    description: "Bold coral primary, warm sand page.",
    primaryColor: "#E11D48",
    secondaryColor: "#F43F5E",
    accentColor: "#F59E0B",
    textColor: "#4C0519",
    backgroundColor: "#FFF1F2",
    navbarColor: "#9F1239",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#881337",
    sidebarTextColor: "#FECDD3",
    accentHoverColor: "#D97706",
  },
  {
    presetName: "Lavender",
    presetKey: "lavender",
    description: "Soft violet primary, gentle light chrome.",
    primaryColor: "#7C3AED",
    secondaryColor: "#8B5CF6",
    accentColor: "#D946EF",
    textColor: "#2E1065",
    backgroundColor: "#FAF5FF",
    navbarColor: "#6D28D9",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#5B21B6",
    sidebarTextColor: "#DDD6FE",
    accentHoverColor: "#C026D3",
  },
  {
    presetName: "Forest",
    presetKey: "forest",
    description: "Deep evergreen primary, light sage page.",
    primaryColor: "#15803D",
    secondaryColor: "#4D7C0F",
    accentColor: "#A3E635",
    textColor: "#052E16",
    backgroundColor: "#F7FEE7",
    navbarColor: "#14532D",
    navbarTextColor: "#FFFFFF",
    sidebarColor: "#14532D",
    sidebarTextColor: "#BBF7D0",
    accentHoverColor: "#65A30D",
  },
  {
    presetName: "Slate",
    presetKey: "slate",
    description: "Minimal grey-graphite, neutral professional.",
    primaryColor: "#334155",
    secondaryColor: "#64748B",
    accentColor: "#F59E0B",
    textColor: "#0F172A",
    backgroundColor: "#F1F5F9",
    navbarColor: "#1E293B",
    navbarTextColor: "#E2E8F0",
    sidebarColor: "#334155",
    sidebarTextColor: "#CBD5E1",
    accentHoverColor: "#D97706",
  },
];
