import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import lookupsRouter from "./lookups.js";
import mastersRouter from "./masters.js";
import transactionsRouter from "./transactions.js";
import reportsRouter from "./reports.js";
import employeesRouter from "./employees.js";
import salaryEntriesRouter from "./salary-entries.js";
import dashboardRouter from "./dashboard.js";
import dailyProductionRouter from "./daily-production.js";
import yarnReceiptsRouter from "./yarn-receipts.js";
import dailyDeliveriesRouter from "./daily-deliveries.js";
import plausibilityRouter from "./plausibility.js";
import unreconciledNavRouter from "./unreconciled-nav.js";
import machineMaintenanceRouter from "./machine-maintenance.js";
import factoryMaintenanceRouter from "./factory-maintenance.js";
import machineAnalyticsRouter from "./machine-analytics.js";
import partyAnalyticsRouter from "./party-analytics.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(lookupsRouter);
router.use(mastersRouter);
router.use(transactionsRouter);
router.use(reportsRouter);
router.use(employeesRouter);
router.use(salaryEntriesRouter);
router.use(dashboardRouter);
router.use(dailyProductionRouter);
router.use(yarnReceiptsRouter);
router.use(dailyDeliveriesRouter);
router.use(plausibilityRouter);
router.use(unreconciledNavRouter);
router.use(machineMaintenanceRouter);
router.use(factoryMaintenanceRouter);
router.use(machineAnalyticsRouter);
router.use(partyAnalyticsRouter);

export default router;
